SET NAMES utf8mb4;
USE power_demo;

CREATE TABLE IF NOT EXISTS raw_legacy_monthly_report (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  source_file_name VARCHAR(255) NULL,
  source_report_type VARCHAR(64) NOT NULL DEFAULT 'legacy_monthly_report',
  source_row_key VARCHAR(64) NOT NULL,
  report_code VARCHAR(128) NULL,
  report_name VARCHAR(255) NULL,
  stat_month CHAR(7) NULL,
  metric_code VARCHAR(128) NULL,
  metric_name VARCHAR(255) NULL,
  entity_code VARCHAR(128) NULL,
  entity_name VARCHAR(255) NULL,
  entity_level VARCHAR(64) NULL,
  parent_code VARCHAR(128) NULL,
  parent_name VARCHAR(255) NULL,
  time_scope VARCHAR(64) NULL,
  value DECIMAL(20,4) NULL,
  unit VARCHAR(64) NULL,
  generation_total DECIMAL(20,4) NULL,
  generation_trial DECIMAL(20,4) NULL,
  grid_total DECIMAL(20,4) NULL,
  grid_trial DECIMAL(20,4) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_raw_legacy_monthly_report_row (source_row_key),
  KEY idx_raw_legacy_monthly_report_stat_month (stat_month),
  KEY idx_raw_legacy_monthly_report_metric_code (metric_code),
  KEY idx_raw_legacy_monthly_report_entity_code (entity_code)
);

CREATE TABLE IF NOT EXISTS semantic_legacy_monthly_fact (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  stat_month CHAR(7) NULL,
  report_code VARCHAR(128) NULL,
  report_name VARCHAR(255) NULL,
  metric_code VARCHAR(255) NULL,
  metric_name VARCHAR(255) NULL,
  metric_group VARCHAR(64) NULL,
  time_scope VARCHAR(64) NULL,
  energy_type_lv1 VARCHAR(128) NULL,
  energy_type_lv2 VARCHAR(128) NULL,
  entity_code VARCHAR(128) NULL,
  entity_name VARCHAR(255) NULL,
  entity_level VARCHAR(64) NULL,
  parent_entity_code VARCHAR(128) NULL,
  parent_entity_name VARCHAR(255) NULL,
  category_code VARCHAR(255) NULL,
  category_path VARCHAR(512) NULL,
  value DECIMAL(20,4) NULL,
  unit VARCHAR(64) NULL,
  source_table VARCHAR(128) NOT NULL,
  source_row_key VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_semantic_legacy_monthly_fact_row (source_row_key),
  KEY idx_semantic_legacy_monthly_fact_stat_month (stat_month),
  KEY idx_semantic_legacy_monthly_fact_metric_code (metric_code),
  KEY idx_semantic_legacy_monthly_fact_entity_name (entity_name)
);
